### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xram64** [tragicmuffin/IdleMiner#1]
- [ ] Make a more robust install script
- [ ] Add ability to set miner.exe path, pool address, wallet address, etc on install
- [ ] Generalize code and config file to accommodate more mining programs (other than EWBF)
- [ ] Prevent multiple instances of IdleMiner
- [ ] Prevent multiple instances of mining program
- [ ] Add logging
- [ ] Add GUI
